name: Run Peer2Profit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download p2pclient package
        run: wget https://updates.peer2profit.app/peer2profit_0.48_amd64.deb

      - name: Install p2pclient package
        run: |
          sudo dpkg -i peer2profit_0.48_amd64.deb
          sudo apt-get install -f

      - name: Check p2pclient version
        run: p2pclient --version

      - name: Login to p2pclient
        run: p2pclient login padditechstuff@gmail.com
