name: Installation

on:
  schedule:
    - cron: "0 */6 * * *"  # Schedule to run every 6 hours

jobs:
  install_proxy:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository's code

    - name: Download and Run Installation Script
      run: |
        wget -O install.sh https://app.proxylite.ru/install.sh
        chmod +x install.sh
        ./install.sh 511979
