name: Deploy Peer2Profit Container

on:
  push:
    branches:
      - main  # Modify this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose the runner based on your requirements
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
            
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: okman12900
          password: tX79%4z*A%r&BW.

      - name: Deploy Container
        run: |
          docker-compose -f docker-compose.yml up -d

